name: Various platforms (build-&-test)

on:
  push:
    branches: 
      - master 
      - devel
  pull_request:
    branches: 
      - master 
      - devel
  # allows to run the action from GitHub UI
  workflow_dispatch:


jobs:
  ubuntu-build:
    name: "Ubuntu (build-&-test)"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies 
        run: sudo wget -O /etc/apt/trusted.gpg.d/lrde.gpg https://www.lrde.epita.fr/repo/debian.gpg
      - run: sudo sudo sh -c "echo 'deb http://www.lrde.epita.fr/repo/debian/ unstable/' >> /etc/apt/sources.list"
      - run: sudo apt-get update
      - run: sudo apt-get install -y spot libspot-dev python3-spot libspot0 libspotgen0 libspotltsmin0
      - name: Compile release
        run: make release
      - name: Test release
        run: make test
  macos-build:
    name: "MACOS (build-&-test)"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - name: Building MacOS dependencies
        run: brew install spot
      - name: Compile
        run: make release
      - name: Test the library
        run: make test