#!/bin/bash

# Script to batch test generated TELA automata with kofola complement algorithms
# Works with automata generated by generate_random_tela.sh

set -e

# Default parameters
AUTOMATA_DIR="random_tela_automata"
KOFOLA_BINARY=""
OUTPUT_DIR="test_results"
ALGORITHM="ncsb"
TIMEOUT=30

# Function to display usage
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Batch test generated TELA automata with kofola complement algorithms.

OPTIONS:
    -d, --automata-dir DIR      Directory containing .hoa automata files (default: $AUTOMATA_DIR)
    -k, --kofola-binary PATH    Path to kofola binary (default: auto-detect from build)
    -o, --output-dir DIR        Output directory for test results (default: $OUTPUT_DIR)
    -a, --algorithm ALG         Complement algorithm to test (default: $ALGORITHM)
                               Available: ncsb, ncsb-delay, rank, safra, mh, etc.
    -t, --timeout SECONDS      Timeout for each test in seconds (default: $TIMEOUT)
    --stats-only               Only collect statistics, don't run full complement
    -h, --help                  Display this help message

EXAMPLES:
    # Test all automata in default directory with NCSB algorithm
    $0

    # Test with specific kofola binary and algorithm
    $0 -k ./build/src/kofola -a rank

    # Test with timeout and custom directories
    $0 -d my_automata -o my_results -t 60

    # Just collect statistics without running complement
    $0 --stats-only

EOF
}

# Parse command line arguments
STATS_ONLY=false
while [[ $# -gt 0 ]]; do
    case $1 in
        -d|--automata-dir)
            AUTOMATA_DIR="$2"
            shift 2
            ;;
        -k|--kofola-binary)
            KOFOLA_BINARY="$2"
            shift 2
            ;;
        -o|--output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -a|--algorithm)
            ALGORITHM="$2"
            shift 2
            ;;
        -t|--timeout)
            TIMEOUT="$2"
            shift 2
            ;;
        --stats-only)
            STATS_ONLY=true
            shift
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 1
            ;;
    esac
done

# Auto-detect kofola binary if not provided
if [[ -z "$KOFOLA_BINARY" ]]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    POSSIBLE_PATHS=(
        "$SCRIPT_DIR/../../build/src/kofola"
        "$SCRIPT_DIR/../build/src/kofola"
        "./build/src/kofola"
        "./kofola"
    )
    
    for path in "${POSSIBLE_PATHS[@]}"; do
        if [[ -x "$path" ]]; then
            KOFOLA_BINARY="$path"
            break
        fi
    done
    
    if [[ -z "$KOFOLA_BINARY" ]]; then
        echo "Error: Could not find kofola binary. Please specify with -k option."
        echo "Make sure to build the project first with 'make' in the build directory."
        exit 1
    fi
fi

# Validate inputs
if [[ ! -d "$AUTOMATA_DIR" ]]; then
    echo "Error: Automata directory '$AUTOMATA_DIR' does not exist."
    echo "Run generate_random_tela.sh first to create test automata."
    exit 1
fi

if [[ ! -x "$KOFOLA_BINARY" ]]; then
    echo "Error: Kofola binary '$KOFOLA_BINARY' does not exist or is not executable."
    exit 1
fi

# Check if autfilt is available for statistics
if ! command -v autfilt &> /dev/null; then
    echo "Warning: autfilt not found. Statistics collection will be limited."
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Count automata files
automata_files=("$AUTOMATA_DIR"/*.hoa)
if [[ ! -e "${automata_files[0]}" ]]; then
    echo "Error: No .hoa files found in '$AUTOMATA_DIR'"
    exit 1
fi

num_files=${#automata_files[@]}
echo "Found $num_files automata files in '$AUTOMATA_DIR'"
echo "Using kofola binary: $KOFOLA_BINARY"
echo "Algorithm: $ALGORITHM"
echo "Timeout: ${TIMEOUT}s per test"
echo "Output directory: $OUTPUT_DIR"
echo ""

# Initialize counters and results
successful=0
failed=0
timeouts=0
log_file="$OUTPUT_DIR/batch_test_log.txt"
summary_file="$OUTPUT_DIR/batch_test_summary.txt"

# Initialize log file
cat > "$log_file" << EOF
Kofola Batch Test Log
====================
Started: $(date)
Algorithm: $ALGORITHM
Kofola binary: $KOFOLA_BINARY
Timeout: ${TIMEOUT}s

EOF

# Function to test a single automaton
test_automaton() {
    local input_file="$1"
    local filename=$(basename "$input_file")
    local base_name="${filename%.hoa}"
    local result_file="$OUTPUT_DIR/${base_name}_result.txt"
    
    echo -n "Testing $filename... "
    
    # Collect basic statistics
    local stats=""
    if command -v autfilt &> /dev/null; then
        stats=$(autfilt --stats="%s states, %e edges, %a acc sets" "$input_file" 2>/dev/null || echo "N/A")
    fi
    
    # Log test start
    echo "Testing: $filename ($stats)" >> "$log_file"
    
    if [[ "$STATS_ONLY" == "true" ]]; then
        # Only collect statistics
        if command -v autfilt &> /dev/null; then
            autfilt --stats="File: $filename%nStates: %s%nEdges: %e%nAPs: %p%nAcc sets: %a%nAcc name: %g%n" "$input_file" > "$result_file" 2>&1
            echo "STATS" >> "$log_file"
            echo "STATS"
            ((successful++))
        else
            echo "ERROR (no autfilt)" >> "$log_file"
            echo "ERROR"
            ((failed++))
        fi
        return
    fi
    
    # Run kofola with timeout
    local start_time=$(date +%s)
    if timeout "$TIMEOUT" "$KOFOLA_BINARY" --complement --algorithm="$ALGORITHM" "$input_file" > "$result_file" 2>&1; then
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        echo "SUCCESS (${duration}s)" >> "$log_file"
        echo "SUCCESS (${duration}s)"
        ((successful++))
    else
        local exit_code=$?
        if [[ $exit_code -eq 124 ]]; then
            # Timeout occurred
            echo "TIMEOUT (>${TIMEOUT}s)" >> "$log_file"
            echo "TIMEOUT"
            ((timeouts++))
        else
            # Other error
            echo "FAILED (exit code: $exit_code)" >> "$log_file"
            echo "FAILED"
            ((failed++))
        fi
    fi
    
    echo "" >> "$log_file"
}

# Test all automata
echo "Starting batch test..."
start_time=$(date +%s)

for file in "${automata_files[@]}"; do
    test_automaton "$file"
done

end_time=$(date +%s)
total_duration=$((end_time - start_time))

# Generate summary
cat > "$summary_file" << EOF
Kofola Batch Test Summary
========================

Test completed: $(date)
Total duration: ${total_duration}s
Algorithm tested: $ALGORITHM

Results:
- Total automata: $num_files
- Successful: $successful
- Failed: $failed
- Timeouts: $timeouts

Success rate: $(( (successful * 100) / num_files ))%

Configuration:
- Kofola binary: $KOFOLA_BINARY
- Timeout per test: ${TIMEOUT}s
- Input directory: $AUTOMATA_DIR
- Output directory: $OUTPUT_DIR

EOF

if [[ $failed -gt 0 ]]; then
    echo "" >> "$summary_file"
    echo "Failed automata:" >> "$summary_file"
    grep "FAILED" "$log_file" | cut -d':' -f2 | while read -r line; do
        echo "- $line" >> "$summary_file"
    done
fi

if [[ $timeouts -gt 0 ]]; then
    echo "" >> "$summary_file"
    echo "Timed out automata:" >> "$summary_file"
    grep "TIMEOUT" "$log_file" | cut -d':' -f2 | while read -r line; do
        echo "- $line" >> "$summary_file"
    done
fi

# Display final results
echo ""
echo "Batch test completed!"
echo "Results: $successful successful, $failed failed, $timeouts timeouts"
echo "Success rate: $(( (successful * 100) / num_files ))%"
echo "Total time: ${total_duration}s"
echo ""
echo "Detailed log: $log_file"
echo "Summary report: $summary_file"

# Show sample of successful tests
if [[ $successful -gt 0 ]]; then
    echo ""
    echo "Sample successful test results:"
    echo "------------------------------"
    grep -A2 -B1 "SUCCESS" "$log_file" | head -10
fi

exit 0
